# Import required libraries

In [1]:
import numpy as np 
import pandas as pd

In [2]:
# Read data 
df = pd.read_csv('/kaggle/input/clinvar-conflicting/clinvar_conflicting.csv')
df.head(5)

/tmp/ipykernel_33/2861356829.py:2: DtypeWarning: Columns (0,38,40) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('/kaggle/input/clinvar-conflicting/clinvar_conflicting.csv')

,CHROM,POS,REF,ALT,AF_ESP,AF_EXAC,AF_TGP,CLNDISDB,CLNDISDBINCL,CLNDN,...,SIFT,PolyPhen,MOTIF_NAME,MOTIF_POS,HIGH_INF_POS,MOTIF_SCORE_CHANGE,LoFtool,CADD_PHRED,CADD_RAW,BLOSUM62
0,1,1168180,G,C,0.0771,0.10020,0.1066,MedGen:CN169374,NaN,not_specified,...,tolerated,benign,NaN,NaN,NaN,NaN,NaN,1.053,-0.208682,2.0
1,1,1470752,G,A,0.0000,0.00000,0.0000,"MedGen:C1843891,OMIM:607454,Orphanet:ORPHA9877...",NaN,Spinocerebellar_ataxia_21|not_provided,...,deleterious_low_confidence,benign,NaN,NaN,NaN,NaN,NaN,31.000,6.517838,-3.0
2,1,1737942,A,G,0.0000,0.00001,0.0000,"Human_Phenotype_Ontology:HP:0000486,MedGen:C00...",NaN,Strabismus|Nystagmus|Hypothyroidism|Intellectu...,...,deleterious,probably_damaging,NaN,NaN,NaN,NaN,NaN,28.100,6.061752,-1.0
3,1,2160305,G,A,0.0000,0.00000,0.0000,"MedGen:C1321551,OMIM:182212,SNOMED_CT:83092002...",NaN,Shprintzen-Goldberg_syndrome|not_provided,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22.500,3.114491,NaN
4,1,2160305,G,T,0.0000,0.00000,0.0000,"MedGen:C1321551,OMIM:182212,SNOMED_CT:83092002",NaN,Shprintzen-Goldberg_syndrome,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24.700,4.766224,-3.0

## Exploretion

In [3]:
df.shape

(65188, 46)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 65188 entries, 0 to 65187
Data columns (total 46 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   CHROM               65188 non-null  object
 1   POS                 65188 non-null  int64
 2   REF                 65188 non-null  object
 3   ALT                 65188 non-null  object
 4   AF_ESP              65188 non-null  float64
 5   AF_EXAC             65188 non-null  float64
 6   AF_TGP              65188 non-null  float64
 7   CLNDISDB            65188 non-null  object
 8   CLNDISDBINCL        167 non-null    object
 9   CLNDN               65188 non-null  object
 10  CLNDNINCL           167 non-null    object
 11  CLNHGVS             65188 non-null  object
 12  CLNSIGINCL          167 non-null    object
 13  CLNVC               65188 non-null  object
 14  CLNVI               27659 non-null  object
 15  MC                  64342 non-null  object
 16  ORIGIN              65188 non-null  int64
 17  SSR                 130 non-null    float64
 18  CLASS               65188 non-null  int64
 19  Allele              65188 non-null  object
 20  Consequence         65188 non-null  object
 21  IMPACT              65188 non-null  object
 22  SYMBOL              65172 non-null  object
 23  Feature_type        65174 non-null  object
 24  Feature             65174 non-null  object
 25  BIOTYPE             65172 non-null  object
 26  EXON                56295 non-null  object
 27  INTRON              8803 non-null   object
 28  cDNA_position       56304 non-null  object
 29  CDS_position        55233 non-null  object
 30  Protein_position    55233 non-null  object
 31  Amino_acids         55184 non-null  object
 32  Codons              55184 non-null  object
 33  DISTANCE            108 non-null    float64
 34  STRAND              65174 non-null  float64
 35  BAM_EDIT            31969 non-null  object
 36  SIFT                24836 non-null  object
 37  PolyPhen            24796 non-null  object
 38  MOTIF_NAME          2 non-null      object
 39  MOTIF_POS           2 non-null      float64
 40  HIGH_INF_POS        2 non-null      object
 41  MOTIF_SCORE_CHANGE  2 non-null      float64
 42  LoFtool             60975 non-null  float64
 43  CADD_PHRED          64096 non-null  float64
 44  CADD_RAW            64096 non-null  float64
 45  BLOSUM62            25593 non-null  float64
dtypes: float64(12), int64(3), object(31)
memory usage: 22.9+ MB

In [5]:
df.isna().sum()

CHROM                     0
POS                       0
REF                       0
ALT                       0
AF_ESP                    0
AF_EXAC                   0
AF_TGP                    0
CLNDISDB                  0
CLNDISDBINCL          65021
CLNDN                     0
CLNDNINCL             65021
CLNHGVS                   0
CLNSIGINCL            65021
CLNVC                     0
CLNVI                 37529
MC                      846
ORIGIN                    0
SSR                   65058
CLASS                     0
Allele                    0
Consequence               0
IMPACT                    0
SYMBOL                   16
Feature_type             14
Feature                  14
BIOTYPE                  16
EXON                   8893
INTRON                56385
cDNA_position          8884
CDS_position           9955
Protein_position       9955
Amino_acids           10004
Codons                10004
DISTANCE              65080
STRAND                   14
BAM_EDIT              33219
SIFT                  40352
PolyPhen              40392
MOTIF_NAME            65186
MOTIF_POS             65186
HIGH_INF_POS          65186
MOTIF_SCORE_CHANGE    65186
LoFtool                4213
CADD_PHRED             1092
CADD_RAW               1092
BLOSUM62              39595
dtype: int64

In [6]:
df.nunique()

CHROM                    38
POS                   63115
REF                     866
ALT                     458
AF_ESP                 2842
AF_EXAC                6667
AF_TGP                 2087
CLNDISDB               9234
CLNDISDBINCL             93
CLNDN                  9260
CLNDNINCL               101
CLNHGVS               65188
CLNSIGINCL              137
CLNVC                     7
CLNVI                 27654
MC                       90
ORIGIN                   31
SSR                       2
CLASS                     2
Allele                  374
Consequence              48
IMPACT                    4
SYMBOL                 2328
Feature_type              2
Feature                2369
BIOTYPE                   2
EXON                   3264
INTRON                 1929
cDNA_position         13970
CDS_position          13663
Protein_position       7339
Amino_acids            1262
Codons                 2220
DISTANCE                 96
STRAND                    2
BAM_EDIT                  2
SIFT                      4
PolyPhen                  4
MOTIF_NAME                2
MOTIF_POS                 1
HIGH_INF_POS              1
MOTIF_SCORE_CHANGE        2
LoFtool                1195
CADD_PHRED             9324
CADD_RAW              63803
BLOSUM62                  6
dtype: int64

## Dealing with missing values

In [7]:
# Drop columns that contain all values missing or more than 80% missingØ² 
df.drop(['CLNDISDBINCL' ,'CLNDNINCL' ,'CLNSIGINCL' ,'CLNVI' ,'SSR' ,'INTRON' ,'DISTANCE' 
         ,'BAM_EDIT' ,'SIFT' ,'PolyPhen' ,'MOTIF_NAME' ,'MOTIF_POS' ,'HIGH_INF_POS' 
         ,'MOTIF_SCORE_CHANGE' ,'BLOSUM62'] ,axis = 1 ,inplace = True)

In [8]:
# Drop rows that contain NaN .
df.dropna(subset=['MC'], inplace=True)
df.dropna(subset=['SYMBOL'], inplace=True)
df.dropna(subset=['Feature_type'], inplace=True)
df.dropna(subset=['Feature'], inplace=True)
df.dropna(subset=['BIOTYPE'], inplace=True)
df.dropna(subset=['STRAND'], inplace=True)
df.dropna(subset=['CADD_PHRED'], inplace=True)
df.dropna(subset=['CADD_RAW'], inplace=True)
df.dropna(subset=['EXON'], inplace=True)
df.isna().sum()

CHROM                  0
POS                    0
REF                    0
ALT                    0
AF_ESP                 0
AF_EXAC                0
AF_TGP                 0
CLNDISDB               0
CLNDN                  0
CLNHGVS                0
CLNVC                  0
MC                     0
ORIGIN                 0
CLASS                  0
Allele                 0
Consequence            0
IMPACT                 0
SYMBOL                 0
Feature_type           0
Feature                0
BIOTYPE                0
EXON                   0
cDNA_position          0
CDS_position         997
Protein_position     997
Amino_acids         1013
Codons              1013
STRAND                 0
LoFtool             3525
CADD_PHRED             0
CADD_RAW               0
dtype: int64

In [9]:
# Fill NaN in 'LoFtool' with (before + after)/2.
df['LoFtool'] = (df['LoFtool'].fillna(method='ffill') + df['LoFtool'].fillna(method='bfill')) / 2
df.isna().sum()

/tmp/ipykernel_33/1766205807.py:2: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['LoFtool'] = (df['LoFtool'].fillna(method='ffill') + df['LoFtool'].fillna(method='bfill')) / 2

CHROM                  0
POS                    0
REF                    0
ALT                    0
AF_ESP                 0
AF_EXAC                0
AF_TGP                 0
CLNDISDB               0
CLNDN                  0
CLNHGVS                0
CLNVC                  0
MC                     0
ORIGIN                 0
CLASS                  0
Allele                 0
Consequence            0
IMPACT                 0
SYMBOL                 0
Feature_type           0
Feature                0
BIOTYPE                0
EXON                   0
cDNA_position          0
CDS_position         997
Protein_position     997
Amino_acids         1013
Codons              1013
STRAND                 0
LoFtool                6
CADD_PHRED             0
CADD_RAW               0
dtype: int64

In [10]:
df.dropna(subset=['LoFtool'], inplace=True)

In [11]:
# Split 'EXON' colunm to 2 colunms.
df[['EXON_num', 'EXON_total']] = df['EXON'].str.split('/', expand=True)
df.drop(['EXON'] ,axis = 1 ,inplace = True)
df.isna().sum()

CHROM                  0
POS                    0
REF                    0
ALT                    0
AF_ESP                 0
AF_EXAC                0
AF_TGP                 0
CLNDISDB               0
CLNDN                  0
CLNHGVS                0
CLNVC                  0
MC                     0
ORIGIN                 0
CLASS                  0
Allele                 0
Consequence            0
IMPACT                 0
SYMBOL                 0
Feature_type           0
Feature                0
BIOTYPE                0
cDNA_position          0
CDS_position         997
Protein_position     997
Amino_acids         1013
Codons              1013
STRAND                 0
LoFtool                0
CADD_PHRED             0
CADD_RAW               0
EXON_num               0
EXON_total             0
dtype: int64

In [12]:
# Fill NaN in 'cDNA_position' with MEAN.
df['cDNA_position'] = pd.to_numeric(df['cDNA_position'], errors='coerce')
df['cDNA_position'] = df['cDNA_position'].fillna( df['cDNA_position'].mean())

In [13]:
df['cDNA_position']

6        1858.0
7        2159.0
8        3562.0
9        3942.0
10       3842.0
          ...
65183    4035.0
65184    3118.0
65185    1257.0
65186     822.0
65187     791.0
Name: cDNA_position, Length: 54667, dtype: float64

In [14]:
# Fill NaN in 'CDS_position' with MEAN.
df['CDS_position'] = pd.to_numeric(df['CDS_position'], errors='coerce')
df['CDS_position'] = df['CDS_position'].fillna( df['CDS_position'].mean())

In [15]:
# Fill NaN in 'Protein_position' with MEAN.
df['Protein_position'] = pd.to_numeric(df['Protein_position'], errors='coerce')
df['Protein_position'] = df['Protein_position'].fillna( df['Protein_position'].mean())

In [16]:
# Fill NaN in 'Amino_acids' with most frequent value.
most_frequent_value = df['Amino_acids'].mode()[0]
most_frequent_value

'A'

In [17]:
df['Amino_acids'] = df['Amino_acids'].fillna(most_frequent_value)

In [18]:
# Fill NaN in 'Codons' with most frequent value.
most_frequent_value = df['Codons'].mode()[0]
df['Codons'] = df['Codons'].fillna(most_frequent_value)

In [19]:
df.shape

(54667, 32)

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 54667 entries, 6 to 65187
Data columns (total 32 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   CHROM             54667 non-null  object
 1   POS               54667 non-null  int64
 2   REF               54667 non-null  object
 3   ALT               54667 non-null  object
 4   AF_ESP            54667 non-null  float64
 5   AF_EXAC           54667 non-null  float64
 6   AF_TGP            54667 non-null  float64
 7   CLNDISDB          54667 non-null  object
 8   CLNDN             54667 non-null  object
 9   CLNHGVS           54667 non-null  object
 10  CLNVC             54667 non-null  object
 11  MC                54667 non-null  object
 12  ORIGIN            54667 non-null  int64
 13  CLASS             54667 non-null  int64
 14  Allele            54667 non-null  object
 15  Consequence       54667 non-null  object
 16  IMPACT            54667 non-null  object
 17  SYMBOL            54667 non-null  object
 18  Feature_type      54667 non-null  object
 19  Feature           54667 non-null  object
 20  BIOTYPE           54667 non-null  object
 21  cDNA_position     54667 non-null  float64
 22  CDS_position      54667 non-null  float64
 23  Protein_position  54667 non-null  float64
 24  Amino_acids       54667 non-null  object
 25  Codons            54667 non-null  object
 26  STRAND            54667 non-null  float64
 27  LoFtool           54667 non-null  float64
 28  CADD_PHRED        54667 non-null  float64
 29  CADD_RAW          54667 non-null  float64
 30  EXON_num          54667 non-null  object
 31  EXON_total        54667 non-null  object
dtypes: float64(10), int64(3), object(19)
memory usage: 13.8+ MB

In [21]:
df.describe()

,POS,AF_ESP,AF_EXAC,AF_TGP,ORIGIN,CLASS,cDNA_position,CDS_position,Protein_position,STRAND,LoFtool,CADD_PHRED,CADD_RAW
count,5.466700e+04,54667.000000,54667.000000,54667.000000,54667.000000,54667.000000,54667.000000,54667.000000,54667.000000,54667.000000,54667.000000,54667.000000,54667.000000
mean,7.813390e+07,0.013105,0.013065,0.013823,1.366821,0.252145,5099.039379,4934.294960,1641.967361,-0.005543,0.347198,16.773399,2.812065
std,5.997168e+07,0.054491,0.056219,0.056307,6.113072,0.434248,13052.898482,13030.825419,4358.050504,0.999994,0.354502,10.936226,3.068189
min,1.387550e+05,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,-1.000000,0.000069,0.001000,-5.477391
25%,3.249672e+07,0.000000,0.000000,0.000000,1.000000,0.000000,932.000000,739.000000,244.000000,-1.000000,0.028900,8.433500,0.640694
50%,5.976330e+07,0.000000,0.000050,0.000000,1.000000,0.000000,1894.000000,1722.000000,566.000000,-1.000000,0.184000,15.650000,1.909314
75%,1.142756e+08,0.001100,0.001100,0.001400,1.000000,1.000000,4116.000000,4134.000000,1336.000000,1.000000,0.677000,24.800000,4.832487
max,2.476080e+08,0.499000,0.499890,0.499800,513.000000,1.000000,108207.000000,107961.000000,35987.000000,1.000000,1.000000,99.000000,46.556261

In [22]:
# save df_cleaning.
df.to_csv('clinvar_conflicting.csv')